"""auto_generated

Revision ID: 169c6faaf9cc
Revises: d498fc175fcd
Create Date: 2026-08-09 16:44:23.931731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169c6faaf9cc'
down_revision: Union[str, Sequence[str], None] = 'd498fc175fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_telegram_id'))

    op.drop_table('admins')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('access_level', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_telegram_id'))
        batch_op.create_index(batch_op.f('ix_admin_sessions_id'), ['id'], unique=False)
        batch_op.drop_constraint(batch_op.f('admin_sessions_telegram_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['telegram_id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('telegram_id')

    with op.batch_alter_table('admin_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('access_level', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('is_revoked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_admin_tokens_token'))
        batch_op.create_index(batch_op.f('ix_admin_tokens_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['token_hash'])
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['telegram_id'])
        batch_op.drop_column('token')
        batch_op.drop_column('is_used')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_admin_tokens_id'))
        batch_op.create_index(batch_op.f('ix_admin_tokens_token'), ['token'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_revoked')
        batch_op.drop_column('access_level')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('token_hash')

    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_sessions_telegram_id_fkey'), 'users', ['telegram_id'], ['telegram_id'])
        batch_op.drop_index(batch_op.f('ix_admin_sessions_id'))
        batch_op.create_index(batch_op.f('ix_admin_sessions_telegram_id'), ['telegram_id'], unique=False)
        batch_op.drop_column('last_active_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('access_level')
        batch_op.drop_column('user_id')

    op.create_table('admins',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_authorized', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('admins_telegram_id_fkey')),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('admins_pkey'))
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_telegram_id'), ['telegram_id'], unique=False)

    # ### end Alembic commands ###
